server:
  port: 9010

test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: lb://httpbin


spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/httpbin
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
        # =====================================
        # to run server
        # $ wscat --listen 9000
        # to run client
        # $ wscat --connect ws://localhost:8080/echo
        - id: websocket_test
          uri: ws://localhost:9000
          order: 9000
          predicates:
            - Path=/echo
        # =====================================
        - id: default_path_to_httpbin
          uri: ${test.uri}
          order: 10000
          predicates:
            - Path=/**

logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management:
  health:
    redis:
      enabled: false

management.endpoints.web.exposure.include: '*'

route:
  list:
    -
      uri: geoserver-0
      minx: 400000
      miny: 450000
      maxx: 800000
      maxy: 900000
    -
      uri: geoserver-1
      minx: 400000
      miny: 900000
      maxx: 800000
      maxy: 1350000
    -
      uri: geoserver-2
      minx: 800000
      miny: 450000
      maxx: 1200000
      maxy: 900000
    # ...